<?php

########################################################################
# Extension Manager/Repository config file for ext: "ke_questionnaire"
#
# Auto generated by Extension Builder 2012-09-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Questionnaire',
	'description' => 'Fork of Kennziffer LTS 7 version. adapted for LTS 8 aund 9  !! Easily create any type of questionnaire, survey, poll, quiz or eLearning. The results may be evaluated and displayed graphically at any time. See further information - also about the premium version - at www.ke-questionnaire.de',
	'category' => 'plugin',
	'author' => 'kennziffer.com',
	'author_email' => 'info@kennziffer.com',
	'author_company' => 'www.kennziffer.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '9.5.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-9.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>