<?php

declare(strict_types=1);

########################################################################
# Extension Manager/Repository config file for ext: "ke_questionnaire"
#
# Auto generated by Extension Builder 2012-09-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################
$EM_CONF['ke_questionnaire'] = [
	'title' => 'Questionnaire',
	'description' => 'Fork of Kennziffer LTS 7 version. Adapted for LTS 13 !! reduced to the core functionality of a questionnaire. ',
	'category' => 'plugin',
	'author' => 'velletti.de',
	'author_email' => 'typo3@velletti.de',
	'state' => 'beta',
	'version' => '13.4.0',
	'constraints' => [
		'depends' => [
			'typo3' => '13.0.0-13.4.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
