services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Kennziffer\KeQuestionnaire\:
    resource: '../Classes/*'
  Kennziffer\KeQuestionnaire\Reports\FileAccessReport:
    tags:
      - name: reports.report
